### ISSUE TITLE
Missing Upload Functionality

### ISSUE THREAD

**Issue by harshcoder7** [DegChain/Degchain-contracts#1]
**### Required functionalities:-**

 "Write the IPFS storage code to interact with the IPFS network for storing PDF files.", "Implement functions for uploading and retrieving PDFs."

**Comment by vivekup3424** [comment]
I want to implement the IPFS upload functionality, kindly assign me the issue

**Comment by harshcoder7** [comment]
OKkay done

**Comment by harshcoder7** [comment]
Yeah
